CREATE TABLE IF NOT EXISTS market_close_rankings (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  trade_date DATE NOT NULL,
  rank_type VARCHAR(24) NOT NULL COMMENT 'strong|moneyflow',
  rank_no INT NOT NULL,
  symbol VARCHAR(16) NOT NULL,
  market VARCHAR(32) NOT NULL DEFAULT 'A_STOCK_MAIN',
  name VARCHAR(128) NULL,
  sector_name VARCHAR(128) NULL,
  change_1d_pct DECIMAL(10,4) NULL,
  change_3d_pct DECIMAL(10,4) NULL,
  change_5d_pct DECIMAL(10,4) NULL,
  change_10d_pct DECIMAL(10,4) NULL,
  net_main_inflow DECIMAL(24,2) NULL,
  net_main_inflow_pct DECIMAL(10,4) NULL,
  flow_direction VARCHAR(16) NULL,
  source VARCHAR(64) NOT NULL DEFAULT 'market_collector',
  snapshot_time DATETIME NOT NULL,
  raw_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_close_rank_trade_type_symbol (trade_date, rank_type, symbol),
  KEY idx_close_rank_trade_type_rank (trade_date, rank_type, rank_no),
  KEY idx_close_rank_snapshot_time (snapshot_time),
  KEY idx_close_rank_symbol (symbol)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
