CREATE TABLE IF NOT EXISTS watchlist_review_records (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NULL,
  watchlist_id BIGINT UNSIGNED NOT NULL,
  insight_id BIGINT UNSIGNED NOT NULL,
  symbol VARCHAR(16) NOT NULL,
  market VARCHAR(32) NOT NULL DEFAULT 'A_STOCK_MAIN',
  insight_time DATETIME NOT NULL,
  base_price DECIMAL(18,4) NULL,
  price_1d DECIMAL(18,4) NULL,
  price_3d DECIMAL(18,4) NULL,
  price_5d DECIMAL(18,4) NULL,
  return_1d_pct DECIMAL(10,4) NULL,
  return_3d_pct DECIMAL(10,4) NULL,
  return_5d_pct DECIMAL(10,4) NULL,
  expected_direction VARCHAR(16) NOT NULL DEFAULT 'neutral',
  is_accurate TINYINT(1) NULL,
  evaluation_note VARCHAR(255) NULL,
  evaluated_at DATETIME NOT NULL,
  raw_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_watchlist_review_user_insight (user_id, insight_id),
  KEY idx_watchlist_review_user_watchlist_time (user_id, watchlist_id, evaluated_at),
  KEY idx_watchlist_review_symbol_time (symbol, market, evaluated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
