CREATE TABLE IF NOT EXISTS watchlist_review_snapshots (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  snapshot_date DATE NOT NULL,
  snapshot_slot VARCHAR(16) NOT NULL COMMENT 'midday|close|manual',
  snapshot_scope VARCHAR(16) NOT NULL COMMENT 'global|symbol',
  watchlist_id BIGINT UNSIGNED NULL,
  symbol VARCHAR(16) NOT NULL DEFAULT '',
  market VARCHAR(32) NULL,
  name VARCHAR(128) NULL,
  sample_count INT NOT NULL DEFAULT 0,
  accuracy_rate DECIMAL(10,4) NULL,
  avg_return_1d_pct DECIMAL(10,4) NULL,
  avg_return_3d_pct DECIMAL(10,4) NULL,
  avg_return_5d_pct DECIMAL(10,4) NULL,
  win_rate_5d DECIMAL(10,4) NULL,
  score DECIMAL(12,4) NULL,
  series_json JSON NULL,
  source VARCHAR(32) NOT NULL DEFAULT 'review_service',
  snapshot_time DATETIME NOT NULL,
  raw_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_review_snapshot_user_slot_scope_symbol (user_id, snapshot_date, snapshot_slot, snapshot_scope, symbol),
  KEY idx_review_snapshot_user_scope_date (user_id, snapshot_scope, snapshot_date),
  KEY idx_review_snapshot_watchlist (user_id, watchlist_id, snapshot_time),
  KEY idx_review_snapshot_score (user_id, snapshot_scope, score)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
